plugins:
  - node
  - prettier
  - promise
  - import
extends:
  - airbnb-base
  - eslint:recommended
  - plugin:node/recommended
  - plugin:promise/recommended
  - plugin:prettier/recommended
  - plugin:import/errors
  - plugin:import/warnings
env:
  node: true
  es6: true
  jest: true
parserOptions:
  sourceType: module
  ecmaVersion: 2018
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: all
      bracketSpacing: true
      arrowParens: avoid
  node/exports-style:
    - error
    - module.exports
  no-process-env:
    - off
  no-console:
    - off
  comma-dangle:
    - error
    - arrays: always-multiline
      exports: always-multiline
      functions: always-multiline
      imports: always-multiline
      objects: always-multiline
  function-paren-newline:
    - off
  promise/avoid-new:
    - off
  # On Windows uncomment this.
  # linebreak-style:
  #  - error
  #  - windows
settings:
  node:
    allowModules:
      - aws-sdk
